services:
  - type: web
    name: carwash-services-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: GATEWAY_API_URL
        value: https://gateway-api-lztd.onrender.com
    healthCheckPath: /