services:
  - type: web
    name: carwash-services-api
    env: node
    plan: free
    buildCommand: cd services-api && npm install
    startCommand: cd services-api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GATEWAY_API_URL
        sync: false